module.exports = {
    MSG_WRITE: "Unesi",
    MSG_ADD_NEW_BOOK: "Nova knjiga",
    MSG_ADD_QUESTIONS: "Dodaj pitanje",
    MSG_NO_AGE_LEVELS: 5,
    MSG_AGE_LEVEL: "Dob čitaoca",
    MSG_AGE_LEVEL_1: "0-3 godine",
    MSG_AGE_LEVEL_2: "4-7 godina",
    MSG_AGE_LEVEL_3: "8-12 godina",
    MSG_AGE_LEVEL_4: "13-16 godina",
    MSG_AGE_LEVEL_5: "Preko 17 godina",
    MSG_ANSWER: "Odgovor",
    MSG_ANSWERS: "Odgovori",
    MSG_AUTHOR: "Pisac",
    MSG_BOOK: "Knjiga",
    MSG_BOOKS: "Knjige",
    MSG_BOOK_CREATE_SUCC: "Knjiga uspječno unešena!",
    MSG_BOOK_SEARCH: "Pretraga knjiga",
    MSG_BOOKS_LIST : "Lista knjiga",
    MSG_CHOOSE_MANDATORY: "Odaberite...",
    MSG_CANCEL: "Otkaži",
    MSG_CHOOSE: "Odaberite...",
    MSG_CLOSE: "Zatvori",
    MSG_COMMENT: "Pojašnjenje",
    MSG_CONTINUE: "Nastavi od ranije",
    MSG_CORRECT_ANSWER: "Tačan odgovor",
    MSG_CORRECT_ANSWERS: "Tačni odgovori",
    MSG_INCORRECT_ANSWER: "Netačan odgovor",
    MSG_INCORRECT_ANSWERS: "Netačni odgovori",
    MSG_DESCRIPTION: "Opis",
    MSG_DETAILS: "Ostali podaci",
    MSG_DIFFICULTY_LEVEL: "Težina",
    MSG_NO_DIFFICULTY_LEVELS: 3,
    MSG_DIFFICULTY_LEVEL_1: "Lagano",
    MSG_DIFFICULTY_LEVEL_2: "Normalno",
    MSG_DIFFICULTY_LEVEL_3: "Zahtjevno",
    MSG_EDIT: "Obradi",
    MSG_ENTER: "Unesite",
    MSG_ENTER_ANSWER: "Unesite odgovor",
    MSG_ENTER_MANDATORY: "Unesite",
    MSG_ENTER_YEAR: "Unesite godinu",
    MSG_ENTER_NUMBER: "Unesite broj",
    MSG_ENTER_BOOK_SUMMARY: "Unesite kratak opis knjige (ne više od tri rečenice)",
    MSG_ENTER_QUESTION: "Unesite pitanje",
    MSG_ENTER_QUESTION_NO_QUESTION_MARK: "Unesite pitanje (bez upitnika na kraju)",
    MSG_EXISTING_BOOKS: "Postojeće knjige",
    MSG_GENRE: "Žanr",
    MSG_GENRES: "Žanrovi",
    MSG_GENRE_FIRST: "Glavni žanr...",
    MSG_GENRE_SECOND: "Dodatni žanr...",
    MSG_GENRE_THIRD: "Dodatni žanr...",
    MSG_NO_GENRES: 26,
    MSG_GENRE_1: 'roman',
    MSG_GENRE_2:'zbirka poezije',
    MSG_GENRE_3: 'knjiga za djecu',
    MSG_GENRE_4: 'psihološki roman',
    MSG_GENRE_5: 'narodna poezija',
    MSG_GENRE_6: 'istorija',
    MSG_GENRE_7: 'putopis',
    MSG_GENRE_8: 'biografija',
    MSG_GENRE_9: 'autobiografija',
    MSG_GENRE_10: 'narodna poezija',
    MSG_GENRE_11: 'zbirka pripovjetki',
    MSG_GENRE_12: 'satira',
    MSG_GENRE_13: 'drama',
    MSG_GENRE_14: 'kratke priče',
    MSG_GENRE_15: 'pozorišna drama',
    MSG_GENRE_16: 'komedija',
    MSG_GENRE_17: 'ratna',
    MSG_GENRE_18: 'pozorišna komedija',
    MSG_GENRE_19: 'patriotska',
    MSG_GENRE_20: 'stručna',
    MSG_GENRE_21: 'nauka',
    MSG_GENRE_22: 'sport',
    MSG_GENRE_23: 'umjetnost',
    MSG_GENRE_24: 'društvena tematika',
    MSG_GENRE_25: 'avanture',
    MSG_GENRE_26: 'ljubavna',
    MSG_INVALID_AGE_LEVEL: "Unesite prigodnu dob čitaoca",
    MSG_INVALID_DIFFICULTY_LEVEL: "Unesite težinu",
    MSG_INVALID_TITLE: "Unesite naslov knjige",
    MSG_INVALID_AUTHOR: "Unesite autora knjige",
    MSG_INVALID_GENRE: "Unesite jedan žanr knjige, a po mogućnosti i dva ili tri.",
    MSG_INVALID_NATIONALITY: "Unesite pripadnost knjige",
    MSG_INVALID_PUBLICATION_YEAR: "Godina mora biti izmedju 1 i 2022. Za antičke knjige stavite 1.",
    MSG_INVALID_QUESTION_TYPE: "Unesite tip pitanja",
    MSG_INVALID_QUESTION: "Unesite pitanje",
    MSG_INVALID_NO_ANSWERS: "Unesite ukupan broj odgovora",
    MSG_INVALID_NO_CORRECT_ANSWERS: "Unesite broj tačnih odgovora",
    MSG_INVALID_SUMMARY: "Unesite zažetak knjige",
    MSG_MANDATORY_FIELDS: "Polja sa crnim okvirom se moraju popuniti",
    MSG_NATIONALITY: "Književna pripadnost",
    MSG_NATIONALITY_FIRST: "Prva pripadnost...",
    MSG_NATIONALITY_SECOND: "Dodatna pripadnost...",
    MSG_NO_NATIONAITIES: 33,
    MSG_NATIONALITY_1: 'bosanska',
    MSG_NATIONALITY_2: 'srpska',
    MSG_NATIONALITY_3: 'hrvatska',
    MSG_NATIONALITY_4: 'crnogorska',
    MSG_NATIONALITY_5: 'slovenačka',
    MSG_NATIONALITY_6: 'makedonska',
    MSG_NATIONALITY_7: 'vojvođanska',
    MSG_NATIONALITY_8: 'albanska',
    MSG_NATIONALITY_9:  'američka',
    MSG_NATIONALITY_10: 'britanska',
    MSG_NATIONALITY_11: 'evropska',
    MSG_NATIONALITY_12: 'francuska',
    MSG_NATIONALITY_13: 'italijanska',
    MSG_NATIONALITY_14: 'njemačka',
    MSG_NATIONALITY_15: 'ruska',
    MSG_NATIONALITY_16: 'španska',
    MSG_NATIONALITY_17: 'turska',
    MSG_NATIONALITY_18: 'starogrčka',
    MSG_NATIONALITY_19: 'ruska',
    MSG_NATIONALITY_20: 'arapska',
    MSG_NATIONALITY_21: 'egipatska',
    MSG_NATIONALITY_22: 'južnoamerička',
    MSG_NATIONALITY_23: 'kineska',
    MSG_NATIONALITY_24: 'japanska',
    MSG_NATIONALITY_25: 'persijska',
    MSG_NATIONALITY_26: 'balkanska',
    MSG_NATIONALITY_27: 'sjeverno-evropska',
    MSG_NATIONALITY_28: 'istočno-evropska',
    MSG_NATIONALITY_29: 'azijska',
    MSG_NATIONALITY_30:  'afrička',
    MSG_NATIONALITY_31:  'magribska',
    MSG_NATIONALITY_32: 'bliskoistočna',
    MSG_NATIONALITY_33: 'ostala',
    MSG_NEW_QUESTION: "Novo pitanje",
    MSG_NO_QUESTIONS: "Broj postojećih pitanja:",
    MSG_NO_ANSWERS: "Broj odgovora",
    MSG_NO_CORRECT_ANSWERS: "Broj tačnih odgovora",
    MSG_NUMBER_CHAPTER: "Broj poglavlja",
    MSG_SEARCH_RESULTS: "Rezultati pretrage",
    MSG_OPTIONAL: "Po potrebi",
    MSG_PENDING: "Obrada u toku",
    MSG_PERIOD: "Književni pravac",
    MSG_PERIOD_FIRST: "Glavni književni pravac...",
    MSG_PERIOD_SECOND: "Dodatni književni pravac...",
    MSG_NO_PERIODS: 10,
    MSG_PERIOD_1:'renesansa',
    MSG_PERIOD_2:'prosvjetiteljstvo',
    MSG_PERIOD_3:'romantizam',
    MSG_PERIOD_4:'realizam',
    MSG_PERIOD_5:'naturalizam',
    MSG_PERIOD_6:'simbolizam',
    MSG_PERIOD_7:'impresionizam',
    MSG_PERIOD_8:'moderna književnost',
    MSG_PERIOD_9:'postmodernizam',
    MSG_PERIOD_10:'egzistencijalizam',
    MSG_PLS_CLICK_ON_BOOK: "Izaberite knjigu...",
    MSG_PLS_CLICK_ON_QUESTION: "Izaberite pitanje",
    MSG_PLS_CLICK_ON_QUESTION_OR_CREATE_QUESTION: "Izaberite pitanje ili dodajte pitanje",
    MSG_PUBLICATION_YEAR: "Godina objavljivanja",
    MSG_PUBLISHED: "Završena",
    MSG_QUESTION: "Pitanje",
    MSG_QUESTIONS: "Pitanja",
    MSG_QUESTIONS_EXISTING: "Postojeća pitanja",
    MSG_QUESTION_CATEGORY_BREAKDOWN: "Broj pitanja po kategoriji",
    MSG_QUESTION_CATEGORY_1: "Likovi",
    MSG_QUESTION_CATEGORY_2: "Mjesto radnje",
    MSG_QUESTION_CATEGORY_3: "Vrijeme radnje",
    MSG_QUESTION_CATEGORY_4: "Radnja",
    MSG_QUESTION_CATEGORY_5: "Poruke",
    MSG_QUESTION_CATEGORY: "Tip pitanja",
    MSG_QUESTION_SAVE_SUCC: "Pitanje uspješno unešeno!",
    MSG_QUESTION_FORM_HEADER: "Pitanja za knjigu: ",
    MSG_QUESTIONS_NOT_EXIST: "Nema pitanja",
    MSG_EQUESTION_UPDATE_FAILURE: "Greška prilikom unosa pitanja",
    MSG_RESET: "Resetuj",
    MSG_SAVE: "Sačuvaj",
    MSG_SEARCH: "Traži",
    MSG_SEARCH_BY_TITLE: "Unesi naslov knjige za pretragu",
    MSG_STATS: "Statistika",
    MSG_SUMMARY: "Sažetak",
    MSG_TITLE: "Naslov",
    MSG_UNACCENTED: "Ne koristim slova č,ć,š,ž,đ",
    MSG_WAIT_UNTIL_QUESTIONS_LOAD: "Pitanja se učitavaju ..."


    
    
    
    
    
    
    
    

    
    
    
}