module.exports = {
    MIN_NO_QUESTIONS_PER_BOOK: 12,
    MIN_NO_QUESTIONS_CATEGORY_1: 3,
    MIN_NO_QUESTIONS_CATEGORY_2: 2,
    MIN_NO_QUESTIONS_CATEGORY_3: 1,
    MIN_NO_QUESTIONS_CATEGORY_4: 3,
    MIN_NO_QUESTIONS_CATEGORY_5: 1,
    NO_QUESTION_CATEGORIES: 5,
    BACKEND_SERVER_URL: 'http://www.citajmo.ba:8080'
}